CREATE TABLE clients (
    client_id                     VARCHAR(255) PRIMARY KEY,
    client_secret_hash            TEXT,
    redirect_uris                 JSON NOT NULL,
    grant_types                   JSON NOT NULL,
    response_types                JSON NOT NULL,
    token_endpoint_auth_method     VARCHAR(64) NOT NULL,
    allowed_scopes                 JSON NOT NULL,
    default_scopes                 JSON,
    subject_type                   VARCHAR(16) NOT NULL,
    jwks_uri                       TEXT,
    jwks                           JSON,
    require_pkce                   BOOLEAN NOT NULL DEFAULT false,
    require_code_challenge         BOOLEAN NOT NULL DEFAULT false,
    client_name                    TEXT,
    client_uri                     TEXT,
    logo_uri                       TEXT,
    contacts                       JSON,
    tos_uri                        TEXT,
    policy_uri                     TEXT,
    software_id                    TEXT,
    software_version               TEXT,
    application_type               TEXT,
    sector_identifier_uri          TEXT,
    id_token_signed_response_alg   TEXT,
    default_max_age                INTEGER,
    require_auth_time              BOOLEAN,
    default_acr_values             JSON,
    initiate_login_uri              TEXT,
    request_uris                   JSON,
    code_challenge_method           VARCHAR(16),
    registration_access_token_hash  TEXT,
    client_id_issued_at             BIGINT,
    client_secret_expires_at        BIGINT
) ENGINE=InnoDB;
